"""Generate a reviewer-friendly application packet PDF in memory."""

from __future__ import annotations

from io import BytesIO
from datetime import datetime, timezone
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def generate_packet(session_id: str, fields: list[dict[str, Any]], documents: list[dict[str, Any]],
                    readiness: dict[str, Any], calculation: dict[str, Any] | None = None) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=.6 * inch, leftMargin=.6 * inch,
                            topMargin=.55 * inch, bottomMargin=.55 * inch)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="Brand", parent=styles["Title"], textColor=colors.HexColor("#173F5F"), fontSize=22))
    styles.add(ParagraphStyle(name="Notice", parent=styles["BodyText"], backColor=colors.HexColor("#FFF7ED"),
                              borderColor=colors.HexColor("#F59E0B"), borderWidth=1, borderPadding=8, leading=14))
    styles.add(ParagraphStyle(name="Footer", parent=styles["BodyText"], alignment=TA_CENTER, textColor=colors.HexColor("#64748B"), fontSize=8))
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    story = [Paragraph("RealDoor", styles["Brand"]), Paragraph("Application Readiness Packet", styles["Heading2"]),
             Paragraph(f"Reference: {session_id} &nbsp;&nbsp; Generated: {generated}", styles["BodyText"]), Spacer(1, 12),
             Paragraph("REVIEWER NOTICE: This packet organizes submitted documents and transparent calculations. It does not determine eligibility, approval, denial, ranking, or priority.", styles["Notice"]), Spacer(1, 14)]

    story.extend([Paragraph("Confirmed profile", styles["Heading2"])])
    confirmed = [field for field in fields if field.get("confirmed")]
    rows = [["Field", "Confirmed value", "Source", "Confidence"]] + [
        [item["name"].replace("_", " ").title(), str(item.get("value", "")), item.get("source_document", ""), f"{float(item.get('confidence', 0))*100:.0f}%"]
        for item in confirmed
    ]
    if len(rows) == 1:
        rows.append(["—", "No fields confirmed", "—", "—"])
    table = Table(rows, colWidths=[1.25*inch, 1.8*inch, 2.25*inch, .75*inch], repeatRows=1)
    table.setStyle(_table_style())
    story.extend([table, Spacer(1, 14), Paragraph("Document inventory", styles["Heading2"])])
    doc_rows = [["Document", "Type", "Status", "Confidence"]] + [[d["file_name"], d["document_type"], d["status"], f"{float(d.get('confidence') or 0)*100:.0f}%"] for d in documents]
    table = Table(doc_rows, colWidths=[2.55*inch, 1.5*inch, 1.1*inch, .85*inch], repeatRows=1)
    table.setStyle(_table_style())
    story.extend([table, Spacer(1, 14), Paragraph(f"Readiness checklist — {readiness['score']}%", styles["Heading2"]),
                  Paragraph(readiness["disclaimer"], styles["Notice"]), Spacer(1, 8)])
    check_rows = [["Status", "Item", "Detail"]] + [[item.status.upper(), item.label, item.detail] for item in readiness["items"]]
    table = Table(check_rows, colWidths=[1.0*inch, 2.1*inch, 3.1*inch], repeatRows=1)
    table.setStyle(_table_style())
    story.append(table)
    if calculation:
        story.extend([Spacer(1, 14), Paragraph("Calculation ledger", styles["Heading2"]),
                      Paragraph(str(calculation.get("formula", "No calculation recorded.")), styles["Code"]),
                      Paragraph(str(calculation.get("citation", "")), styles["BodyText"])])
    story.extend([Spacer(1, 24), Paragraph("Generated by RealDoor • Human review required", styles["Footer"])])
    doc.build(story)
    return buffer.getvalue()


def _table_style() -> TableStyle:
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#173F5F")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8), ("LEADING", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), .35, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6), ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ])

