[theme]
primaryColor = "#205D59"
backgroundColor = "#F5F7F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17252B"
font = "sans serif"

[server]
maxUploadSize = 20
headless = true

[browser]
gatherUsageStats = false

